# Generated by Django 2.0.2 on 2018-03-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0003_auto_20180309_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='app_article.Tag', verbose_name='标签'),
        ),
    ]
