# Generated by Django 2.0.2 on 2018-03-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0005_auto_20180309_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='update_time',
            new_name='updated_time',
        ),
    ]
