# Generated by Django 2.0.2 on 2018-03-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0006_auto_20180309_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='word',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tag',
            name='word',
            field=models.CharField(default='', max_length=64),
        ),
    ]
